version: '3'
services:
  app:
    build: ./app 
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql://username:password@mysql/dbname

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
